### ISSUE TITLE
Spice up login page

### ISSUE THREAD

**Issue by evancofer** [evancofer/reddigest-scalafied#3]

**Comment by evancofer** [comment]
Login page currently looks terrible. Need to find a way for the forms to not look so bad.

**Comment by tinathefatwhale** [comment]
Why is the scala "form" passing `<dl>` and other list style tags (That's why it looks so bad)? I'm going to make a plain html page with the forms in them and have them post to the appropriate pages. Also, we could have them do ajax calls instead.

**Comment by tinathefatwhale** [comment]
oh never mind i guess.

**Comment by evancofer** [comment]
The problem is with the forms "helper" constructor. We could write a custom one, but I think I found a way to make it look not too bad.

**Comment by evancofer** [comment]
Also, pull from master, as the last merge brought in a lot of purely html changes.

**Comment by tinathefatwhale** [comment]
I think the page I created could resolve some issues, but I'm unsure. I've committed it to my branch if you want to check it out.

**Comment by tinathefatwhale** [comment]
done-a-roo
