### ISSUE TITLE
Create client side side handling of failed account actions (Client/Server)

### ISSUE THREAD

**Issue by evancofer** [evancofer/reddigest-scalafied#5]
User actions are things like login, logout, account registration, or account deletion. Need to have some windows or a div on client side that appears when a user actions fail. Need to write a view template for this case.

**Comment by tinathefatwhale** [comment]
The failed login/registration aspect would be a lot easier if we used ajax calls instead of get-ing to a new page.

**Comment by evancofer** [comment]
If it will making responsiveness better, I will look into getting an embedded router setup for the view templates, as that's how to do ajax in the play framework. We already have json writers for users so validation etc. shouldn't be too big of a problem if I can figure out the routing.
For reference: https://www.playframework.com/documentation/2.2.x/ScalaJavascriptRouting

 Also,We will need some functions in scripts.js to handle responses. I expect that there will be different ones for registration, login, and account deletion. I will implement these serverside and write a json reader/writer for them for the server.

| failure.type | login | addUser | removeUser |
| --- | --- | --- | --- |
| authentication | x |  | x |
| username.empty | x | x | x |
| username.taken |  | x |  |
| username.short |  | x |  |
| password.empty | x | x | x |
| password.weak |  | x |  |
| password.mismatch |  | x |  |

I will look into implementing these server side, if you can write the response parsing for the client.

Stylistically, I think we should go for something like bit bucket has for bad password attempts, or maybe something simpler, where its just text right about the field that is bad, and then right above the form if a general authentication failure.

**Comment by evancofer** [comment]
Fixed.
